sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: FYehwEqEkWl8UrSQLUZ+il4wSd+zudrZnBwa+zuEYd3tf00b18idi3estgp6yMgEAxrbU1IQ1qBRDoDxUa0jU0wfL1NwYQ9iGxgaAp/i2TRh4G3mWWxFZOdUHMHBKU2UHv0jOg1EgAK9xQHeNfaA/9KCgp5wW3oPGpS302uQxk2MUpPEtGaV3sXm51D+vo9XisoqHqrCKvQYtOdX9dcIvM6egqzWcYR3huRQPf+CxqRzN8gaZ7txUORAq/1+xuMqibhx0JMwa3ucp2+NueUk3ChvRpS7rBhsm1s5GXNJGHAUPgaYww0xCVkvm9sdnOQluqc39IWWmCd1xcZrD+oDyfsJtXj5TIUU/V1l1Z9uNcfPh72mn75eXKCbjsHCN3viGy/wJfPFpkZ7nSCrXpnVjpLehYQF6BhtLXAdaI/5uKfSBr/g391EQMaXBziKs4SVDQXL3UrCzQUqe7bKdP5Kq1o4uiC46Y0UECJzqS4vl1ze5gc01JWgaz9N08gVFgGPgHXGmWMfL7OYczS0KqRNURlHA3lp+/I3Fy42Pkk+Aujk2y6n1ITk/dsNk8lTR9jh8KxBcsVkYHG1Lx1lFOZ7PSAiSHTrhmnpeBajxookpZSGKe8SLVhISPJUfKN683iwCcrYVBvkjTR0kZXKSCCWy3+rhUSVbtKAVkADYLPrITs=
  - secure: PmbtHW+9zD2AAYeBx7KUI315+nWc7s9gWyUdSXnCGhW05CBKRXc5N4jOTwt6/pV8rmAGJCfv9iRtMplgxoQCauKolvEj3r6XYidC7KsDfEGiZ9HCBqtOIrvALw/g4i4+goBAC/5jArlTvuVwUygNsUihgtDsDsmmzo/7YuV4qokTBX0QgSQgYoop+DZNul9wkmpkbjx/c5qVOu+5RjxSSc8dr1ewTThsxoA7WazYqUdE9ejnFPL/3fUX7WXcbglPb6S+R4pdFIoAdgYHjWymssJdqaHjsLRxA4rCR40RQvqcukeejJiIBLKbtyJiUf+I58wa7inrBAgnZ+W4vi9Tc5IvOWyp76dFAfpdrnKXgxCIN8NZi21UuSsgVzc/vb8L/R7UiZhw9A7puAeA2c/l+kl1uIXBV9cbGaKzRo3RzRcFV12kyneDIcK7YyxoJIXCfBbK+RfEWMAe4gWxM0jLz4LWv4mEfxO6AeUkfMxwm0ZwxRZSPcl/TOUmps3okbJ10Z/lsiUVuQrjCmodLIE81F5ur4/stGwGT2GppaNtagaQ1PdNNC7DJVh8GZfK3f+HzCD5h6fMJOZ8aiGA2Fb6AvrYEacx//JXqNzNVAr8J83G1zgIcVpOSF0YTqq1i78x8sE0hdFKTd0ze6FyNCI5Tk60OLdRArWXqpjt+h8SAZY=
notifications:
  slack:
    on_success: change
    rooms:
     - secure: a1UURhhtAZc378/t8ATjphvMiSfH+xAk/9cb5+fQObQZ+Rm5cBIrIsZRQPR2WFIJZAw7sjucbeBFCHOc50uawpyd/esZuqNCs/0pI38UZRsx4tEOlVtt7p582X8dHg5A/HSw9GdAw8Tuciw+N/gTBuDDM3pyjLuOG9aGJfJaI4Wm157DsF7KOO30v/kGGoJmkK5yuI7mbm0VYrQljl0vva43v8201HzHOBaJNC7wHglPBXu+HDxrQ3E+uo9ewO08ZBu5j5k/SWrAWYH9k3LszD7jFCvo4w/7isMoJyQ0WIMovwdpg+3uATLUzeP0odrCLCQ6lws+mu0C59SLzaqy8Ngoao9eStMEj8wqPVkwdroAdO98AGxkgZLA+a4tlQipZS8Qc2mWYHlJbRSEJBW41aK7G+M9amOZ/EvSDo1oRmTo9kRkUFo6OWYgvNJ6D3C6TgpvsQcP13jXQkV5FsX8igHAU2cQ8qM7LdxXFz46u4zUHWLAIACkf1DCBRjgibDonZkenczRPt7zCuOF7mCUwrbPkTQrj4dXONhEQ1hDgxJuLQeeCEDkstceb0moSCd4+XrOCUml5SIqvLL9lVg+6BCB5isWTQ/UQEMVGhjhxwhWhWrZThW26F6em0OqjUQyk0LaGwM6HtAnw2AFV6IXbi87yInGwmTS+m9XKACA2I8=
